= duplic8r =
Quickly provision my favourite _command line_ environment.

== Background ==
Whenever I set up a new *N*X environment, it takes me a some time to
get my environment _'just right'_ I'm sick of it.

To fix it, I just run:
.Installation Instructions
[source, sh]
----
  $ git clone https://github.com/axler8r/duplic8r.git ~/.duplic8r
  $ ~/.duplic8r/install
----
to configure my favourite Linux or macOS shell and gnome environment.


== Table of Contents ==
* <<Install, Install>>
* <<Use, Use>>
* <<Contribute, Contribute>>
* <<License, License>>
* <<Notes, Notes>>


[#Install]
== Install ==


[#Use]
== Use ==


[#Contribute]
== Contribute ==

=== Copyright Waiver ===


=== Authors ===


[#License]
== License ==
This is free and unencumbered public domain software. For more
information, see http://unlicense.org/ or the accompanying UNLICENSE
file.


== Blah ==
I use zsh on my own workstations and servers.  By far the most
common shell I encounter in the wild is Bash.  In light of that,
the rules I make here for use of zsh applies to my usage profile.

I almost exclusively use zsh to perform tasks at the command line.
ZSH to makes my life easier.  I prefer to work from the shell and
not to grab the mouse to accomplish every task.

.Things I do a lot
* Use git
* Use docker
* Start and manage tmux sessions
* Use Neovim
* Update or upgrade my system
* Read man-pages
* SSH into other systems
* Start applicaitons like Visual Studio Code
* Run REPLs
* Compile source code
* Install, configure and uinstall shit using snap, apt or asdf
* cat, sed, awk and jq file content
* Download stuff with wget or curl
* Search for stuff
* Montior system activites or system health
* Perform filesystem related activities
* Manage virtual environments
* Occasionally experiment with interesting tech or whatever is new and shiny

.Things I don't do
* Extensive scripting

.My programming languages
* Elixir/Erlang
* Python
* C#
* Rust
* Kotlin/Scala

.Programming languages I am interested in
* Reason
* Nim

.Goals
* Know where to put what
* Keep files clean and minimalistic and easy to manage


== STARTUP ORDER ==
When zsh starts it reads global configs that I don't mess with. I am
interested the following ones:
.StartupFilesTable
[cols="1,1"]
|===
| File       | Startup
|~/.zshenv   | allways. It is read every time I USE a shell like<br>
               running a script.
|~/.zprofile | if it is a login shell — i.e. I have logged in via<br>
               ssh or GDM and opened a shell (terminal). Running<br>
               a shell, not logged in, would be a script kicked<br>
               off by cron at 03:00 while I am logged off and<br>
               fast asleep in bed. In that case, ~/.zprofile will<br>
               NOT be read. It is read every time I open a shell.
|~/.zshrc    | if it is an interactive shell — i.e. I can type<br>
               commands in a terminal and see the results. It is<br>
               read every time I open a shell.
|~/.zshlogin | if it is a login shell. It is read every time I<br>
               open a shell.
|===


== GUIDANCE ==
Check out THIS link:
  https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout


== WHERE TO PUT WHAT ==
ONLY use files. ~/.zshenv and ~/.zshrc, unless instructions for
configuration purposes indicate that one of the other zsh config
files should be used.

.Configuraiton Locations
* Environment variables go into ~/.zshenv
* PATH manipulation of any kind goes into ~/.zshenv
* Stuff related to shell use like PAGER and EDITOR goes into ~/.zshrc


.Note.OrderOfStuffInDOTzshrc
== ORDER OF STUFF IN ~/.zshrc ==
* completion system
* shell options
* shit that is NOT a function, alias or prompt but has to do only with shell use like LS_COLORS or MANWIDTH
* funcitons   — split out into ~/.zshfunctions and source
* aliases     — split out into ~/.zshaliases and source
* prompt
* stuff that must happen after prompt is set
