# COMPLETION OPTIONS
zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' '+r:|[._-]=* r:|=*'
zstyle :compinstall filename '/home/axl/.zshrc'i
autoload -Uz compinit
compinit


# FEATURES
autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line


# SETTINGS
HISTFILE=$HOME/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
setopt no_beep
setopt pushd_silent
setopt pushd_to_home
setopt append_history
setopt bang_hist
bindkey -v


# CONFIGURATIONS
[[ -f $HOME/.zshfunction ]] && source $HOME/.zshfunction
[[ -f $HOME/.zshalias ]] && source $HOME/.zshalias
[[ -f $HOME/.zshprompt ]] && source $HOME/.zshprompt


# STUFF THAT MUST BE SET AFTER PROMPT
if [[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]
then
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]]
then
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=cyan"
    source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if [[ -f $HOME/.zsh-hsmw/history-search-multi-word.plugin.zsh ]]
then
    source $HOME/.zsh-hsmw/history-search-multi-word.plugin.zsh
fi

