# COMPLETIONS
zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' '+r:|[._-]=* r:|=*'
zstyle :compinstall filename '/home/axl/.zshrc'i
autoload -Uz compinit
compinit


# FEATURES
autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line


# SETTINGS
HISTFILE=$HOME/.zsh_history
HISTSIZE=65536
export SAVEHIST=$HISTSIZE
setopt append_history
setopt bang_hist
setopt extended_history
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_space
setopt autocd
setopt no_beep
setopt pushd_silent
setopt pushd_to_home
bindkey -v


# DEFAULTS
[[ -f $(which nvim) ]] && EDITOR=$(which nvim)
[[ -f $(which nvim) ]] && VISUAL=$(which nvim)


# APPLICATIONS
[[ -f $HOME/.asdf/asdf.sh ]] && source $HOME/.asdf/asdf.sh
[[ -f $HOME/.fzf.zsh ]] && source $HOME/.fzf.zsh
[[ -f $HOME/.bin/z.sh ]] && source $HOME/.bin/z.sh


# CONFIGURATIONS
[[ -f $HOME/.zshfunction ]] && source $HOME/.zshfunction
[[ -f $HOME/.zshalias ]] && source $HOME/.zshalias
[[ -f $HOME/.zshprompt ]] && source $HOME/.zshprompt

